// <auto-generated />
using System;
using Avancerad.NET_SlutProjekt.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Avancerad.NET_SlutProjekt.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240520165308_Fixat lite med jwt")]
    partial class Fixatlitemedjwt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClassLibrary.Appointment", b =>
                {
                    b.Property<int>("AppointId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointId"));

                    b.Property<int>("AppointmentDurationMinutes")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("StartingTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("AppointId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            AppointId = 1,
                            AppointmentDurationMinutes = 60,
                            CompanyId = 1,
                            CreationDate = new DateTime(2024, 5, 19, 16, 53, 8, 340, DateTimeKind.Utc).AddTicks(7737),
                            CustomerId = 1,
                            Description = "Undersökning för att hitta eventuella skador/sjukdomar",
                            StartingTime = new DateTime(2024, 5, 25, 16, 53, 8, 340, DateTimeKind.Utc).AddTicks(7736),
                            Title = "Undersökning",
                            UpdateDate = new DateTime(2024, 5, 20, 16, 53, 8, 340, DateTimeKind.Utc).AddTicks(7737)
                        },
                        new
                        {
                            AppointId = 2,
                            AppointmentDurationMinutes = 30,
                            CompanyId = 2,
                            CreationDate = new DateTime(2024, 5, 18, 16, 53, 8, 340, DateTimeKind.Utc).AddTicks(7741),
                            CustomerId = 2,
                            Description = "Träningspass med våran PT",
                            StartingTime = new DateTime(2024, 5, 27, 16, 53, 8, 340, DateTimeKind.Utc).AddTicks(7741),
                            Title = "PT-Pass",
                            UpdateDate = new DateTime(2024, 5, 20, 16, 53, 8, 340, DateTimeKind.Utc).AddTicks(7742)
                        });
                });

            modelBuilder.Entity("ClassLibrary.ChangeLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AppointId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ChangedAtDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ChangeLogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Action = "Skapad",
                            AppointId = 1,
                            ChangedAtDate = new DateTime(2024, 5, 20, 16, 53, 8, 340, DateTimeKind.Utc).AddTicks(7760),
                            CompanyId = 1,
                            CustomerId = 1,
                            Details = "Möte skapad för Anna Andersson"
                        },
                        new
                        {
                            Id = 2,
                            Action = "Skapad",
                            AppointId = 2,
                            ChangedAtDate = new DateTime(2024, 5, 20, 16, 53, 8, 340, DateTimeKind.Utc).AddTicks(7762),
                            CompanyId = 2,
                            CustomerId = 2,
                            Details = "Möte skapad för Karl Karlsson"
                        });
                });

            modelBuilder.Entity("ClassLibrary.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyId"));

                    b.Property<string>("CompanyEmail")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CompanyId");

                    b.HasIndex("UserId");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            CompanyId = 1,
                            CompanyEmail = "fbg@sjukvård.se",
                            CompanyName = "FBG SJUKVÅRD",
                            UserId = 1
                        },
                        new
                        {
                            CompanyId = 2,
                            CompanyEmail = "contact@friskissvettis.se",
                            CompanyName = "Friskis & Svettis",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("ClassLibrary.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CustomerId");

                    b.HasIndex("UserId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            CreationDate = new DateTime(2024, 5, 10, 16, 53, 8, 340, DateTimeKind.Utc).AddTicks(7675),
                            Email = "AnnaAndersson@hotmail.com",
                            FirstName = "Anna",
                            LastName = "Andersson",
                            Phone = "0788995544",
                            UpdateDate = new DateTime(2024, 5, 20, 16, 53, 8, 340, DateTimeKind.Utc).AddTicks(7688),
                            UserId = 2
                        },
                        new
                        {
                            CustomerId = 2,
                            CreationDate = new DateTime(2024, 5, 12, 16, 53, 8, 340, DateTimeKind.Utc).AddTicks(7690),
                            Email = "KarlKarlsson@hotmail.com",
                            FirstName = "Karl",
                            LastName = "Karlsson",
                            Phone = "+4698765432",
                            UpdateDate = new DateTime(2024, 5, 20, 16, 53, 8, 340, DateTimeKind.Utc).AddTicks(7690),
                            UserId = 3
                        });
                });

            modelBuilder.Entity("ClassLibrary.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            PasswordHash = "password",
                            Role = "Admin",
                            Username = "elf"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            PasswordHash = "password",
                            Role = "User",
                            Username = "peter"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            PasswordHash = "password",
                            Role = "Customer",
                            Username = "isac"
                        });
                });

            modelBuilder.Entity("ClassLibrary.Appointment", b =>
                {
                    b.HasOne("ClassLibrary.Company", "Company")
                        .WithMany("Appointments")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClassLibrary.Customer", "Customer")
                        .WithMany("Appointments")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ClassLibrary.Company", b =>
                {
                    b.HasOne("ClassLibrary.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClassLibrary.Customer", b =>
                {
                    b.HasOne("ClassLibrary.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClassLibrary.Company", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("ClassLibrary.Customer", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
