// <auto-generated />
using System;
using Avancerad.NET_SlutProjekt.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Avancerad.NET_SlutProjekt.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClassLibrary.Appointment", b =>
                {
                    b.Property<int>("AppointId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointId"));

                    b.Property<int>("AppointmentDurationMinutes")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("StartingTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("AppointId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            AppointId = 1,
                            AppointmentDurationMinutes = 60,
                            CompanyId = 1,
                            CreationDate = new DateTime(2024, 5, 19, 12, 12, 26, 23, DateTimeKind.Utc).AddTicks(6434),
                            CustomerId = 1,
                            Description = "Meeting to discuss project requirements.",
                            StartingTime = new DateTime(2024, 5, 25, 12, 12, 26, 23, DateTimeKind.Utc).AddTicks(6433),
                            Title = "Consultation Meeting",
                            UpdateDate = new DateTime(2024, 5, 20, 12, 12, 26, 23, DateTimeKind.Utc).AddTicks(6435)
                        },
                        new
                        {
                            AppointId = 2,
                            AppointmentDurationMinutes = 30,
                            CompanyId = 2,
                            CreationDate = new DateTime(2024, 5, 18, 12, 12, 26, 23, DateTimeKind.Utc).AddTicks(6437),
                            CustomerId = 2,
                            Description = "Review of the initial design drafts.",
                            StartingTime = new DateTime(2024, 5, 27, 12, 12, 26, 23, DateTimeKind.Utc).AddTicks(6437),
                            Title = "Design Review",
                            UpdateDate = new DateTime(2024, 5, 20, 12, 12, 26, 23, DateTimeKind.Utc).AddTicks(6438)
                        });
                });

            modelBuilder.Entity("ClassLibrary.ChangeLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AppointId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ChangedAtDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ChangeLogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Action = "Created",
                            AppointId = 1,
                            ChangedAtDate = new DateTime(2024, 5, 20, 12, 12, 26, 23, DateTimeKind.Utc).AddTicks(6451),
                            CompanyId = 1,
                            CustomerId = 1,
                            Details = "Appointment created for John Wall"
                        },
                        new
                        {
                            Id = 2,
                            Action = "Created",
                            AppointId = 2,
                            ChangedAtDate = new DateTime(2024, 5, 20, 12, 12, 26, 23, DateTimeKind.Utc).AddTicks(6454),
                            CompanyId = 2,
                            CustomerId = 2,
                            Details = "Appointment created for Mary Jane"
                        });
                });

            modelBuilder.Entity("ClassLibrary.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyId"));

                    b.Property<string>("CompanyEmail")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CompanyId");

                    b.HasIndex("UserId");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            CompanyId = 1,
                            CompanyEmail = "info@techsolutions.com",
                            CompanyName = "Tech Solutions Inc.",
                            UserId = 1
                        },
                        new
                        {
                            CompanyId = 2,
                            CompanyEmail = "contact@innovativedesigns.com",
                            CompanyName = "Innovative Designs LLC",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("ClassLibrary.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CustomerId");

                    b.HasIndex("UserId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            CreationDate = new DateTime(2024, 5, 10, 12, 12, 26, 23, DateTimeKind.Utc).AddTicks(6391),
                            Email = "john.wall@hotmail.com",
                            FirstName = "John",
                            LastName = "Wall",
                            Phone = "+4634567890",
                            UpdateDate = new DateTime(2024, 5, 20, 12, 12, 26, 23, DateTimeKind.Utc).AddTicks(6397),
                            UserId = 2
                        },
                        new
                        {
                            CustomerId = 2,
                            CreationDate = new DateTime(2024, 5, 12, 12, 12, 26, 23, DateTimeKind.Utc).AddTicks(6399),
                            Email = "mary.jane@hotmail.com",
                            FirstName = "Mary",
                            LastName = "Jane",
                            Phone = "+4698765432",
                            UpdateDate = new DateTime(2024, 5, 20, 12, 12, 26, 23, DateTimeKind.Utc).AddTicks(6399),
                            UserId = 3
                        });
                });

            modelBuilder.Entity("ClassLibrary.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            PasswordHash = "password123",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            PasswordHash = "hejhej456",
                            Role = "User",
                            Username = "user1"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            PasswordHash = "user2",
                            Role = "User",
                            Username = "user2"
                        });
                });

            modelBuilder.Entity("ClassLibrary.Appointment", b =>
                {
                    b.HasOne("ClassLibrary.Company", "Company")
                        .WithMany("Appointments")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClassLibrary.Customer", "Customer")
                        .WithMany("Appointments")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ClassLibrary.Company", b =>
                {
                    b.HasOne("ClassLibrary.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClassLibrary.Customer", b =>
                {
                    b.HasOne("ClassLibrary.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClassLibrary.Company", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("ClassLibrary.Customer", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
